### ISSUE TITLE
sluggi is missing the extension-key property in the composer.json

### ISSUE THREAD

**Issue by Scopestyle** [wazum/sluggi#60]
This is a new error shown in TYPO3 10.4.16:

> In future versions of TYPO3, it will be mandatory for extensions to provide a composer.json file. This will be needed to identify an extension and works as a replacement for the ext_emconf.php. Therefore, the composer.json file must also include the extension key under "extra > typo3/cms > extension-key". Please add a composer.json, including the extension-key property, in the corresponding extension folder. You can use the auto-generated proposal below and update the composer.json file extension. 

It would be good practice to provide this key per default.

**Comment by sypets** [comment]
@Scopestyle Which version of sluggi did you use? Because the latest "master" has this: https://github.com/wazum/sluggi/blob/master/composer.json

Also, the latest 2.03 tag: https://github.com/wazum/sluggi/blob/2.0.3/composer.json

----

see also documentation: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html

**Comment by Scopestyle** [comment]
@sypets I'm using the latest available in the TER (2.0.1)
